# Generated by Django 4.2.4 on 2024-01-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'authorised_group',
            },
        ),
        migrations.CreateModel(
            name='StoreCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Store_categories',
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Store_product',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('employee', models.BooleanField(default=False)),
                ('email', models.EmailField(error_messages={'unique': 'This email has already been registered'}, help_text='Enter a valid email address', max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Store_UserModel',
            },
        ),
    ]
