# Generated by Django 3.2 on 2024-01-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_storeproduct_costprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, default='Address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, default='City', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, default='Country', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered'}, help_text='Enter a valid email address', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, default='User', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, default='Phone', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='postalcode',
            field=models.CharField(blank=True, default='Postal Code', max_length=50, null=True),
        ),
    ]
